### ISSUE TITLE
Workaround `8ce24bc` broken

### ISSUE THREAD

**Issue by yacchin1205** [NII-cloud-operation/Jupyter-LC_docker#92]
With the latest scipy-notebook image https://hub.docker.com/layers/jupyter/scipy-notebook/x86_64-2023-05-29/images/sha256-2c52b398664bdbc31977f9f66d2cf3ff8754886d421e2bfc256411de94610f87?context=explore (maybe) , the workaround commit https://github.com/NII-cloud-operation/Jupyter-LC_docker/commit/8ce24bcd55609828dd7a236d27bc714ad5f0669b seems to be broken.

When the following image is executed, the tornado server becomes unresponsive with the following error message immediately after starting the container.
After a few minutes, a timeout occurs and the problem seems to improve.

https://hub.docker.com/layers/niicloudoperation/notebook/latest/images/sha256-1565b9ddf66ba813b14140ec4c8b0c6bbf2db1382f4762f602e3c00f406cdcb9?context=repo

```
Exception in callback Task.task_wakeup(<Future finis...2d9"\r\n\r\n'>)
handle: <Handle Task.task_wakeup(<Future finis...2d9"\r\n\r\n'>)>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-23' coro=<HTTP1ServerConnection._server_request_loop() running at /opt/conda/lib/python3.10/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /api/co...c2d9"\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /opt/conda/lib/python3.10/site-packages/tornado/ioloop.py:685]> while another task <Task pending name='Task-1' coro=<KernelManager._async_start_kernel() running at /opt/conda/lib/python3.10/site-packages/jupyter_client/manager.py:82>> is being executed.
Exception in callback Task.task_wakeup(<Future finis...2d9"\r\n\r\n'>)
handle: <Handle Task.task_wakeup(<Future finis...2d9"\r\n\r\n'>)>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-21' coro=<HTTP1ServerConnection._server_request_loop() running at /opt/conda/lib/python3.10/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /notebo...c2d9"\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /opt/conda/lib/python3.10/site-packages/tornado/ioloop.py:685]> while another task <Task pending name='Task-108' coro=<RequestHandler._execute() running at /opt/conda/lib/python3.10/site-packages/tornado/web.py:1786> cb=[_HandlerDelegate.execute.<locals>.<lambda>() at /opt/conda/lib/python3.10/site-packages/tornado/web.py:2434]> is being executed.
```

When I revert the commit, this problem will no longer occur.
But https://github.com/jupyter/notebook/issues/6878 occurs as before.

**Comment by yacchin1205** [comment]
Could be related to: https://github.com/jupyter/jupyter_core/pull/353
